version: '3'
services:
  express:
    build:
      context: .
    ports:
      - '5000:5000'
    networks:
      - app-network
    container_name: express

  react:
    build:
      context: ./client
    ports:
      - '3000:3000'
    networks:
      - app-network
    container_name: react

networks:
  app-network:
    driver: bridge
